export const CHAT_REQUEST = 'CHAT_REQUEST';
export const CHAT_SUCCESS = 'CHAT_SUCCESS';
export const CHAT_FAILURE = 'CHAT_FAILURE';


export const CHAT_GROUP_REQUEST = 'CHAT_GROUP_REQUEST';
export const CHAT_GROUP_SUCCESS = 'CHAT_GROUP_SUCCESS';
export const CHAT_GROUP_FAILURE = 'CHAT_GROUP_FAILURE';


export const GET_ALL_CHATS_REQUEST = 'GET_ALL_CHATS_REQUEST';
export const GET_ALL_CHATS_SUCCESS = 'GET_ALL_CHATS_SUCCESS';
export const GET_ALL_CHATS_FAILURE = 'GET_ALL_CHATS_FAILURE';