export const CREATE_NEW_MESSAGES_REQUEST = 'CREATE_NEW_MESSAGES_REQUEST';
export const CREATE_NEW_MESSAGES_SUCCESS = 'CREATE_NEW_MESSAGES_SUCCESS';
export const CREATE_NEW_MESSAGES_FAILURE = 'CREATE_NEW_MESSAGES_FAILURE';

export const GET_ALL_MESSAGES_REQUEST = 'GET_ALL_MESSAGES_REQUEST';
export const GET_ALL_MESSAGES_SUCCESS = 'GET_ALL_MESSAGES_SUCCESS';
export const GET_ALL_MESSAGES_FAILURE = 'GET_ALL_MESSAGES_FAILURE';


export const ADD_MESSAGE='ADD_MESSAGE'